### ISSUE TITLE
Proyekt versiyalamasi iki yerde ferqli gorsenir

### ISSUE THREAD

**Issue by ShahriyarR** [mmzeynalli/integrify#11]
Burda 1.0.0:
https://github.com/mmzeynalli/integrify/blob/main/integrify/__init__.py

Burda ise 1.0.2:
https://github.com/mmzeynalli/integrify/blob/main/pyproject.toml#L7

Hell usulu:
Cox boyuk ehtimal poetry avtomatik versiyani `__init__.py`-dan goture bilir, ona baxa bilersiniz.

**Comment by mmzeynalli** [comment]
Ele ona gore o problem var, Poetry dynamic versioning ede bilmirmish, sora yadimdan chixdi qaldi orda, deyishmeyi unutdum. Silecem

**Comment by mmzeynalli** [comment]
Elave extension ile olur ancaq
