### ISSUE TITLE
Proyekt folder strukturu PEP-e uygun gelmir.

### ISSUE THREAD

**Issue by ShahriyarR** [mmzeynalli/integrify#12]
Proyekt folder strukturunda `root` folder teyin olunmayib.
Best practice deyir ki, kod ucun root folder `src` olmalidir.

https://packaging.python.org/en/latest/tutorials/packaging-projects/

Bu template-den de istifade etmek olar:
https://github.com/ShahriyarR/py-project-template

**Comment by mmzeynalli** [comment]
Muellim, mene chox maraqlidi, bes niye FastAPI ve Pydantic-de tema bele deyil? Bir de bele etsem, import nece olacaq?

**Comment by ShahriyarR** [comment]
Importlar birbasha installationdan gelecek, yani meselen src/integrify install olandan sonra onsuz da integrify kimi paketlenir.
from integrify qalir oz yerinde.

Bu videoda biraz danishmisham folder strukturu haqda, hemcinin arxitektura ve testability haqda:
https://youtu.be/wrtCo2fBoD0?t=225
