### ISSUE TITLE
Python requirement differs from the ruff config

### ISSUE THREAD

**Issue by ShahriyarR** [mmzeynalli/integrify#7]
In `pyproject.toml`:

```
[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^2.8.2"
httpx = "^0.27.2"
```

But for ruff:

```
[tool.ruff]
target-version = "py311"
line-length = 100
```

Better to make the Python versions consistent. If we want backward compatibility, then we need to remove the new things from the code base such as StrEnum which comes from Python 3.11 only.

**Comment by mmzeynalli** [comment]
Azərbaycanca davam edək) Python versiyalarının üstündə işləyəcəm hələ

**Comment by ShahriyarR** [comment]
Yox :dagger:
